---
- hosts: '{{ hosts_all }}'
  connection: ssh
  remote_user: root
  gather_facts: '{{ gather }}'

  # define the variables
  vars:
    hosts_all: all
    gather: yes

  # tasks - playbook that copies the /etc/ansible/hosts file to /home/ansible
  tasks:
  - name: playbook that copies the /etc/ansible/hosts file to /home/ansible
    copy:
      src: /etc/ansible/hosts
      dest: /home/ansible
      owner: root
      group: root
      mode: 0644
    ignore_errors: yes
    tags:
      - copy_file_ansible
    register: copy_out
  - debug: msg="stdout={{ copy_out }}"
  - debug: msg="stderr={{ copy_out }}"

  # playbook that Installs httpd package using yum
  - name: install apache server using the ansible
    yum:
      name: httpd
      state: latest
    when: ansible_os_family == "RedHat"
    tags:
      - apache_install
    ignore_errors: yes
    register: apache_out
  - debug: msg="stdout={{ apache_out }}"
  - debug: msg="stderr={{ apache_out }}"

  # playbook that uses yum and the with_items to install the following packages
  - name: playbook that uses yum and the with_items to install the following packages
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - httpd
      - php
      - php-mysql
      - elinks
    tags:
      - lemp_stack
    register: lemp_out
  - debug: msg="stdout={{ lemp_out }}"
  - debug: msg="stderr={{ lemp_out }}"

# Exercise: Ansible Plays and Playbooks (Number One)
